os: Visual Studio 2015 RC
shallow_clone: true
environment:
    DNX_FEED: https://www.nuget.org/api/v2
install:
    - ps: Invoke-WebRequest https://api.nuget.org/downloads/nuget.exe -OutFile nuget.exe
build_script:
    - nuget restore AppVeyorSample.sln
    - nuget install xunit.runner.console -ExcludeVersion -Version 2.1.0-beta3-build3019 -OutputDirectory packages
    - nuget install xunit.runner.msbuild -ExcludeVersion -Version 2.1.0-beta3-build3019 -OutputDirectory packages
    - dnvm install 1.0.0-beta5-12103 -u
    - dnu restore
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - msbuild AppVeyorSample.sln /m:4 /nologo /v:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - RunAllTests
test: off
