os: Visual Studio 2015 RC
shallow_clone: true
configuration: Release
platform: Any CPU
environment:
    DNX_FEED: https://www.nuget.org/api/v2
install:
    - ps: Invoke-WebRequest https://api.nuget.org/downloads/nuget.exe -OutFile nuget.exe
build_script:
    - nuget restore AppVeyorSample.sln
    - dnvm install 1.0.0-beta4
    - dnu restore
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - msbuild AppVeyorSample.sln /m:4 /nologo /v:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test: off
