image: Visual Studio 2017 RC
shallow_clone: true
install:
    - ps: Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
build_script:
    - nuget restore AppVeyorSample.sln
    - dotnet restore AppVeyorSample.sln
    - nuget install xunit.runner.console -ExcludeVersion -Pre -OutputDirectory packages
    - nuget install xunit.runner.msbuild -ExcludeVersion -Pre -OutputDirectory packages
    - msbuild AppVeyorSample.sln /m:4 /nologo /v:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - RunAllTests
test: off
